services:
  postgres:
    image: postgres:15
    container_name: library-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
