server.port=8080
spring.application.name=api-gateway
spring.main.web-application-type=reactive

# Default filters
spring.cloud.gateway.default-filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.default-filters[1]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

# Route: books ? digital-library (Eureka id must be 'digital-library')
spring.cloud.gateway.routes[0].id=books
spring.cloud.gateway.routes[0].uri=lb://digital-library
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/books/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2

# Route: auth ? auth-service
spring.cloud.gateway.routes[1].id=auth
spring.cloud.gateway.routes[1].uri=lb://auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[2].id=test-log
spring.cloud.gateway.routes[2].uri=lb://auth-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/test-log

# Eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_DEFAULT_ZONE:http://discovery-server:8761/eureka/}
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.instance.preferIpAddress=true

# Actuator (routes debug)
management.endpoints.web.exposure.include=health,info,prometheus,metrics,gateway
management.endpoint.gateway.enabled=true

# Timeouts & logs
spring.cloud.gateway.httpclient.connect-timeout=5000
spring.cloud.gateway.httpclient.response-timeout=10s
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty=DEBUG

management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=100ms,300ms,500ms,1s,2s,5s

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.propagation.type=B3

# Export to Zipkin in Docker
management.tracing.export.zipkin.enabled=true
management.tracing.export.zipkin.endpoint=http://zipkin:9411/api/v2/spans

# (nice-to-have) put traceId/spanId in logs
logging.pattern.level=%5p [traceId=%X{traceId:-} spanId=%X{spanId:-}]



