# debug = true

spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

my.values=apple-banana-cherry

my.date-formats[0]=yyyy-MM-dd
my.date-formats[1]=dd/MM/yyyy
my.date-formats[2]=MM-dd-yyyy
my.time-formats[0]=HH:mm:ss
my.time-formats[1]=hh:mm a
