input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if !("@timestamp" in [@metadata]) {
    mutate { add_field => { "ingested_at" => "%{@timestamp}" } }
  }

  mutate {
    rename => { "logger_name" => "logger" }
    rename => { "thread_name"  => "thread" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug } # helpful when debugging Logstash
}
