services:
  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=7d"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    ports:
      - "9090:9090"
    networks: [observability]

  grafana:
    image: grafana/grafana:11.1.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on: [prometheus]
    networks: [observability]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.2
    ports:
      - "8089:8080"
    networks: [observability]

  zipkin:
    image: openzipkin/zipkin:2.24
    ports:
      - "9411:9411"
    networks: [ observability ]
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9411/zipkin/?limit=1" ]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  prom_data:
  grafana_data:

networks:
  observability: {}

