input {
  tcp {
    port => 5000
    codec => json_lines
  }
  http {
    port => 8081
    additional_codecs => { "application/json" => "json" }
  }
}

filter {
  mutate {
    add_field => {
      "env" => "%{[labels][env]}"
    }
  }
  if [logger_name] =~ "org.springframework.boot.actuate" {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "library-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
